version: '2.2'

services:

  # Core services
  front:
    image: ghcr.io/mailu/nginx:${VERSION}
    restart: always
    env_file: .env
    logging:
      driver: json-file
    ports:
      - "80:80"
      - "443:443"
      - "110:110"
      - "143:143"
      - "993:993"
      - "995:995"
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - "$ROOT/certs:/certs"
      - "$ROOT/overrides/nginx:/overrides:ro"

  resolver:
    image: ghcr.io/mailu/unbound:${VERSION}
    restart: always
    env_file: .env
    networks:
      - default

  admin:
    image: ghcr.io/mailu/admin:${VERSION}
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/dkim:/dkim"
      - "../core/admin/start.py:/start.py:ro"
      - "../core/admin/mailu/sso/forms.py:/app/mailu/sso/forms.py:ro"
      - "../core/admin/mailu/internal/views/auth.py:/app/mailu/internal/views/auth.py:ro"
    depends_on:
      - redis

  imap:
    image: ghcr.io/mailu/dovecot:${VERSION}
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/mail:/mail"
      - "$ROOT/overrides/dovecot:/overrides:ro"
    depends_on:
      - front

  smtp:
    image: ghcr.io/mailu/postfix:${VERSION}
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/mailqueue:/queue"
      - "$ROOT/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver

  antispam:
    image: ghcr.io/mailu/rspamd:${VERSION}
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/filter:/var/lib/rspamd"
      - "$ROOT/dkim:/dkim:ro"
      - "$ROOT/overrides/rspamd:/etc/rspamd/override.d:ro"
    depends_on:
      - front
      - resolver

  # Webmail
  webmail:
    image: ghcr.io/mailu/webmail:${VERSION}
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/webmail:/data"
      - "../webmails/roundcube/login/mailu.php:/var/www/roundcube/plugins/mailu/mailu.php:ro"
      - "../webmails/roundcube/login/localization/en_US.inc:/var/www/roundcube/plugins/mailu/localization/en_US.inc:ro"
      - "../webmails/roundcube/login/skins/elastic/mailu.css:/var/www/roundcube/plugins/mailu/skins/elastic/mailu.css:ro"
      - "../webmails/roundcube/login/skins/classic/mailu.css:/var/www/roundcube/plugins/mailu/skins/classic/mailu.css:ro"
      - "../webmails/roundcube/login/skins/larry/mailu.css:/var/www/roundcube/plugins/mailu/skins/larry/mailu.css:ro"
      - "../webmails/roundcube/login/skins/elastic/templates/password.html:/var/www/roundcube/plugins/mailu/skins/elastic/templates/password.html:ro"
      - "../webmails/roundcube/login/skins/classic/templates/password.html:/var/www/roundcube/plugins/mailu/skins/classic/templates/password.html:ro"
      - "../webmails/roundcube/login/skins/larry/templates/password.html:/var/www/roundcube/plugins/mailu/skins/larry/templates/password.html:ro"
      - "../webmails/roundcube/config/config.inc.php:/conf/config.inc.php:ro"
    depends_on:
      - front

  # Dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "$ROOT/redis:/data"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: $SUBNET
