apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mailu-ingress
  namespace: mailu-mailserver
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  labels:
    app: mailu
    role: mail
    tier: backend
spec:
  tls:
  - hosts:
    - "mailu.opensource.lk"
    secretName: letsencrypt-certs-all # If unsure how to generate these, check out https://github.com/ployst/docker-letsencrypt
  rules:
  - host: "mailu.opensource.lk"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: front
          servicePort: 80
