version: '2'

services:

  front:
    image: mailu/nginx:$VERSION
    restart: always
    env_file: .env
    logging:
      driver: $LOG_DRIVER
    ports:
    - "$BIND_ADDRESS4:80:80"
    - "$BIND_ADDRESS4:443:443"
    - "$BIND_ADDRESS4:110:110"
    - "$BIND_ADDRESS4:143:143"
    - "$BIND_ADDRESS4:993:993"
    - "$BIND_ADDRESS4:995:995"
    - "$BIND_ADDRESS4:25:25"
    - "$BIND_ADDRESS4:465:465"
    - "$BIND_ADDRESS4:587:587"
    - "$BIND_ADDRESS6:80:80"
    - "$BIND_ADDRESS6:443:443"
    - "$BIND_ADDRESS6:110:110"
    - "$BIND_ADDRESS6:143:143"
    - "$BIND_ADDRESS6:993:993"
    - "$BIND_ADDRESS6:995:995"
    - "$BIND_ADDRESS6:25:25"
    - "$BIND_ADDRESS6:465:465"
    - "$BIND_ADDRESS6:587:587"
    volumes:
      - "$ROOT/certs:/certs"
    depends_on:
      - unbound
    dns:
      - 10.177.20.254

  unbound:
    image: mailu/unbound:$VERSION
    restart: always
    networks:
      default:
        ipv4_address: 10.177.20.254

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "$ROOT/redis:/data"
    dns:
      - 10.177.20.254
    depends_on:
      - unbound

  imap:
    image: mailu/dovecot:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/mail:/mail"
      - "$ROOT/overrides:/overrides"
    depends_on:
      - front
      - unbound
    dns:
      - 10.177.20.254

  smtp:
    image: mailu/postfix:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/overrides:/overrides"
    depends_on:
      - front
      - unbound
    dns:
      - 10.177.20.254

  antispam:
    image: mailu/rspamd:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/filter:/var/lib/rspamd"
      - "$ROOT/dkim:/dkim"
      - "$ROOT/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
      - unbound
    dns:
      - 10.177.20.254

  antivirus:
    image: mailu/$ANTIVIRUS:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/filter:/data"
    depends_on:
      - unbound
    dns:
      - 10.177.20.254

  webdav:
    image: mailu/$WEBDAV:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/dav:/data"
    depends_on:
      - unbound
    dns:
      - 10.177.20.254

  admin:
    image: mailu/admin:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/dkim:/dkim"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - redis
      - unbound
    dns:
      - 10.177.20.254

  webmail:
    image: "mailu/$WEBMAIL:$VERSION"
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/webmail:/data"
    depends_on:
      - imap
      - unbound
    dns:
      - 10.177.20.254

  fetchmail:
    image: mailu/fetchmail:$VERSION
    restart: always
    env_file: .env
    depends_on:
      - unbound
    dns:
      - 10.177.20.254

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.177.20.0/24

